Modify to bind with C and create a C example

diff --git a/tests/Makefile b/tests/Makefile
--- a/tests/Makefile
+++ b/tests/Makefile
@@ -8,9 +8,13 @@
 include ../make.inc
 
 F90TESTS = $(shell ls lsmr*.f90 | grep -v Module | sed 's/.f90//g')
+CTESTS = $(patsubst %.c,%,$(wildcard *.c))
+TESTS = $(F90TESTS) $(CTESTS)
 
-all test: $(F90TESTS)
-	@for tst in *.tst; do echo -e "\033[0;33mRunning $$tst\033[0m"; ./$$tst; done
+all test: $(TESTS)
+	@for tst in *.tst; do echo -e "\033[0;33mRunning $$tst\033[0m"; \
+		./$$tst; if [ $$? -eq 1 ]; then \
+			echo -e "\033[0;31mFAILURE\033[0m" && exit 0; fi; done
 
 $(F90TESTS): %: %.f90
 	@echo -e "\033[0;32mCompiling $@\033[0m"
@@ -21,5 +25,9 @@ $(F90TESTS): %: %.f90
 	fi; \
 	${FC} ${FFLAGS} -o $@.tst $$target -I../lib ../lib/$(LIBNAME)
 
+$(CTESTS): %: %.c
+	@echo -e "\033[0;32mCompiling $@\033[0m"
+	${CC} ${CFLAGS} -o $@.tst $@.c -I../lib ../lib/$(LIBNAME) -lgfortran
+
 clean purge:
-	rm -f *.o *.mod $(patsubst %,%.tst,$(F90TESTS))
+	rm -f *.o *.mod $(patsubst %,%.tst,$(TESTS))
